apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: train-ticket

resources:
  - ../../base

patches:
  - path: patches/expose-ui-dashboard.yaml
  - path: patches/expose-gateway.yaml
